[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = COM10
monitor_port = COM10
monitor_speed = 115200

; Kildekatalogen er same mappe som .ino-filen
src_dir = .

lib_deps =
    h2zero/NimBLE-Arduino @ ^2.1.0
    adafruit/Adafruit BNO055 @ ^1.6.3
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BusIO @ ^1.16.1
